# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Model function
#'
#' The main model solving function for a single individual.
#' NOTES:
#' - Do we want infection history to be a vector of infection times?
#' - Tread the contents of infectionHistory as a parameter (ie. exposure type)
#' @param theta NumericVector, the named vector of model parameters
#' @param infectionHistory NumericVector, the vector of 1s and 0s showing presence/absence of infection for each possible time. 
#' @param samplingTime double, the real time that the sample was taken
#' @param strainIsolationTimes NumericVector, the vector of times at which each virus strain circulated
#' @param antigenicMapLong NumericVector, the collapsed cross reactivity map for long term boosting, after multiplying by sigma1
#' @param antigenicMapShort NumericVector, the collapsed cross reactivity map for short term boosting, after multiplying by sigma2
#' @return NumericVector of predicted titres for each strainIsolationTime
#' @useDynLib serosolver
#' @export
infection_model_indiv <- function(theta, infectionHistory, samplingTime, strainIsolationTimes, antigenicMapLong, antigenicMapShort) {
    .Call('_serosolver_infection_model_indiv', PACKAGE = 'serosolver', theta, infectionHistory, samplingTime, strainIsolationTimes, antigenicMapLong, antigenicMapShort)
}

#' Calculate likelihood
#'
#' Calculates the likelihood of a given set of observed titres given predicted titres. Based on truncated discritised normal.
#' @param expected NumericVector, as returned by \code{\link{infection_model_indiv}}
#' @param data NumericVector, the vector of observed titres
#' @param theta NumericVector, the vector of named model parameters, requiring MAX_TITRE and error
#' @return a single log likelihood
#' @export
likelihood_titre <- function(expected, data, theta) {
    .Call('_serosolver_likelihood_titre', PACKAGE = 'serosolver', expected, data, theta)
}

#' Individual likelihood
#'
#' Uses \code{\link{infection_model_indiv}} for a single individual and then calls \code{\link{likelihood_titre}}. Works with NA
#' @param theta NumericVector, the named vector of model parameters
#' @param infectionHistory NumericVector, the vector of 1s and 0s showing presence/absence of infection for each possible time. 
#' @param samplingTimes NumericVector, the vector of real times that samples were taken
#' @param strainIsolationTimes NumericVector, the vector of times at which each virus strain circulated
#' @param antigenicMapLong NumericVector, the collapsed cross reactivity map for long term boosting, after multiplying by sigma1
#' @param antigenicMapShort NumericVector, the collapsed cross reactivity map for short term boosting, after multiplying by sigma2
#' @param titres NumericVector, the vector of observed titres.
#' @return a single log likelihood
#' @useDynLib serosolver
#' @export
individual_likelihood <- function(theta, infectionHistory, samplingTimes, strainIsolationTimes, antigenicMapLong, antigenicMapShort, titres) {
    .Call('_serosolver_individual_likelihood', PACKAGE = 'serosolver', theta, infectionHistory, samplingTimes, strainIsolationTimes, antigenicMapLong, antigenicMapShort, titres)
}

#' Group likelihood
#'
#' Uses \code{\link{individual_likelihood}} for each individual and returns a vector of log likelihoods for each individual
#' @param theta NumericVector, the named vector of model parameters
#' @param infectionHistories NumericMatrix, the matrix of 1s and 0s showing presence/absence of infection for each possible time for each individual 
#' @param indicesA IntegerVector, the range of indices of the titre vector that correspond to each individual (eg. first 5 titres are for indiv 1, indicesA = c(0,5,...)
#' @param indicesB IntegerVector, the range of indices of the sample vector that correspond to each individual (eg. first 2 sampling times are for indiv 1, indicesB = c(0,2,...)
#' @param samplingTimes NumericVector, the vector of real times that samples were taken
#' @param strainIsolationTimes NumericVector, the vector of times at which each virus strain circulated
#' @param antigenicMapLong NumericVector, the collapsed cross reactivity map for long term boosting, after multiplying by sigma1
#' @param antigenicMapShort NumericVector, the collapsed cross reactivity map for short term boosting, after multiplying by sigma2
#' @param titres NumericVector, the vector of observed titres for all individuals.
#' @return a NumericVector of log likelihoods for each individual
#' @useDynLib serosolver
#' @export
group_likelihood_vector <- function(theta, infectionHistories, indicesA, indicesB, samplingTimes, strainIsolationTimes, antigenicMapLong, antigenicMapShort, titres) {
    .Call('_serosolver_group_likelihood_vector', PACKAGE = 'serosolver', theta, infectionHistories, indicesA, indicesB, samplingTimes, strainIsolationTimes, antigenicMapLong, antigenicMapShort, titres)
}

#' Group likelihood
#'
#' Uses \code{\link{individual_likelihood}} for each individual and returns a summed log likelihood for all individuals
#' @param theta NumericVector, the named vector of model parameters
#' @param infectionHistories NumericMatrix, the matrix of 1s and 0s showing presence/absence of infection for each possible time for each individual 
#' @param indicesA IntegerVector, the range of indices of the titre vector that correspond to each individual (eg. first 5 titres are for indiv 1, indicesA = c(0,5,...)
#' @param indicesB IntegerVector, the range of indices of the sample vector that correspond to each individual (eg. first 2 sampling times are for indiv 1, indicesB = c(0,2,...)
#' @param samplingTimes NumericVector, the vector of real times that samples were taken
#' @param strainIsolationTimes NumericVector, the vector of times at which each virus strain circulated
#' @param antigenicMapLong NumericVector, the collapsed cross reactivity map for long term boosting, after multiplying by sigma1
#' @param antigenicMapShort NumericVector, the collapsed cross reactivity map for short term boosting, after multiplying by sigma2
#' @param titres NumericVector, the vector of observed titres for all individuals.
#' @return a single log likelihood
#' @useDynLib serosolver
#' @export
group_likelihood_total <- function(theta, infectionHistories, indicesA, indicesB, samplingTimes, strainIsolationTimes, antigenicMapLong, antigenicMapShort, titres) {
    .Call('_serosolver_group_likelihood_total', PACKAGE = 'serosolver', theta, infectionHistories, indicesA, indicesB, samplingTimes, strainIsolationTimes, antigenicMapLong, antigenicMapShort, titres)
}

